export const AppRoutingPaths = {    
    ACTIVIDADES: "/academia/actividades",
    ALTA_UNICA: "/alumnos/alta-unica",
    BLANK: "",
    CONSULTA: "/alumnos/consulta",
    ERROR: "/error",
    EVALUACIONES: "/academia/evaluaciones",
    FOROS: "/academia/foros",
    GRUPOS: "/academia/grupos",
    HISTORIAL_CAMBIOS: "/alumnos/historial-cambios",
    HOME: "/home",
    LOGIN: "/login",
    MI_PERFIL: '/perfil',
    NOTFOUND: '*',
    RAIZ: "/",
    SESSION_EXPIRED: "/expired",
    VIGENCIAS_DETALLE: "/academia/vigencias/details/:id",
    VIGENCIAS: "/academia/vigencias",
    PERIODOS: "/academia/periodos",
    CURSOS: "/academia/cursos",
    REPORTES: "/academia/reportes",
};
// export type AppRoutingPaths = typeof AppRoutingPaths;